---
- hosts: all
  sudo: yes
  tasks:
    - name: Install Apache. 
      yum: name={{ item }} state=present
      with_items:
      - httpd
      - httpd-devel
    - name: Make sure Apache is started and configure it to run at boot.
      service: name=httpd state=started enabled=yes
